-- Actor

INSERT INTO Actor 
VALUES ('Kathy Bates');
INSERT INTO Actor 
VALUES ('Anjelica Huston');
INSERT INTO Actor 
VALUES ('Julia Roberts');
INSERT INTO Actor 
VALUES ('Meryl Streep');
INSERT INTO Actor 
VALUES ('Joanne Woodward');
INSERT INTO Actor 
VALUES ('Jodie Foster');
INSERT INTO Actor 
VALUES ('Geena Davis');
INSERT INTO Actor 
VALUES ('Laura Dern');
INSERT INTO Actor 
VALUES ('Bette Midler');
INSERT INTO Actor 
VALUES ('Susan Sarandon');
INSERT INTO Actor 
VALUES ('Emma Thompson');
INSERT INTO Actor 
VALUES ('Catherine Deneuve');
INSERT INTO Actor 
VALUES ('Mary McDonnell');
INSERT INTO Actor 
VALUES ('Michelle Pfeiffer');
INSERT INTO Actor 
VALUES ('Holly Hunter');
INSERT INTO Actor 
VALUES ('Angela Bassett');
INSERT INTO Actor 
VALUES ('Stockard Channing');
INSERT INTO Actor 
VALUES ('Debra Winger');
INSERT INTO Actor 
VALUES ('Jessica Lange');
INSERT INTO Actor 
VALUES ('Miranda Richardson');
INSERT INTO Actor 
VALUES ('Winona Ryder');
INSERT INTO Actor 
VALUES ('Elisabeth Shue');
INSERT INTO Actor 
VALUES ('Sharon Stone');
INSERT INTO Actor 
VALUES ('Frances McDormand');
INSERT INTO Actor 
VALUES ('Brenda Blethyn');
INSERT INTO Actor 
VALUES ('Diane Keaton');
INSERT INTO Actor 
VALUES ('Kristin Scott Thomas');
INSERT INTO Actor 
VALUES ('Emily Watson');
INSERT INTO Actor 
VALUES ('Helen Hunt');
INSERT INTO Actor 
VALUES ('Helena Bonham Carter');
INSERT INTO Actor 
VALUES ('Julie Christie');
INSERT INTO Actor 
VALUES ('Judi Dench');
INSERT INTO Actor 
VALUES ('Kate Winslet');
INSERT INTO Actor 
VALUES ('Gwyneth Paltrow');
INSERT INTO Actor 
VALUES ('Cate Blanchett');
INSERT INTO Actor 
VALUES ('Fernanda Montenegro');
INSERT INTO Actor 
VALUES ('Hilary Swank');
INSERT INTO Actor 
VALUES ('Annette Bening');
INSERT INTO Actor 
VALUES ('Janet McTeer');
INSERT INTO Actor 
VALUES ('Julianne Moore');
INSERT INTO Actor 
VALUES ('Natalie Portman');
INSERT INTO Actor 
VALUES ('Nicole Kidman');
INSERT INTO Actor 
VALUES ('Jennifer Lawrence');
INSERT INTO Actor 
VALUES ('Michelle Williams');
INSERT INTO Actor 
VALUES ('Glenn Close');
INSERT INTO Actor 
VALUES ('Viola Davis');
INSERT INTO Actor 
VALUES ('Rooney Mara');
INSERT INTO Actor 
VALUES ('Jessica Chastain');
INSERT INTO Actor 
VALUES ('Emmanuelle Riva');
INSERT INTO Actor 
VALUES ('Quvenzhané Wallis');
INSERT INTO Actor 
VALUES ('Naomi Watts');
INSERT INTO Actor 
VALUES ('Amy Adams');
INSERT INTO Actor 
VALUES ('Sandra Bullock');
INSERT INTO Actor 
VALUES ('Marion Cotillard');
INSERT INTO Actor 
VALUES ('Felicity Jones');
INSERT INTO Actor 
VALUES ('Rosamund Pike');
INSERT INTO Actor 
VALUES ('Reese Witherspoon');
INSERT INTO Actor 
VALUES ('Brie Larson');
INSERT INTO Actor 
VALUES ('Charlotte Rampling');
INSERT INTO Actor 
VALUES ('Saoirse Ronan');
INSERT INTO Actor 
VALUES ('Emma Stone');
INSERT INTO Actor 
VALUES ('Isabelle Huppert');
INSERT INTO Actor 
VALUES ('Ruth Negga');
INSERT INTO Actor 
VALUES ('Sally Hawkins');
INSERT INTO Actor 
VALUES ('Margot Robbie');
INSERT INTO Actor 
VALUES ('Olivia Colman');
INSERT INTO Actor 
VALUES ('Yalitza Aparicio');
INSERT INTO Actor 
VALUES ('Lady Gaga');
INSERT INTO Actor 
VALUES ('Melissa McCarthy');
INSERT INTO Actor 
VALUES ('Renée Zellweger');
INSERT INTO Actor 
VALUES ('Cynthia Erivo');
INSERT INTO Actor 
VALUES ('Scarlett Johansson');
INSERT INTO Actor 
VALUES ('Charlize Theron');
INSERT INTO Actor 
VALUES ('Joan Allen');
INSERT INTO Actor 
VALUES ('Juliette Binoche');
INSERT INTO Actor 
VALUES ('Ellen Burstyn');
INSERT INTO Actor 
VALUES ('Laura Linney');
INSERT INTO Actor 
VALUES ('Halle Berry');
INSERT INTO Actor 
VALUES ('Sissy Spacek');
INSERT INTO Actor 
VALUES ('Salma Hayek');
INSERT INTO Actor 
VALUES ('Diane Lane');
INSERT INTO Actor 
VALUES ('Keisha Castle-Hughes');
INSERT INTO Actor 
VALUES ('Samantha Morton');
INSERT INTO Actor 
VALUES ('Catalina Sandino Moreno');
INSERT INTO Actor 
VALUES ('Imelda Staunton');
INSERT INTO Actor 
VALUES ('Felicity Huffman');
INSERT INTO Actor 
VALUES ('Keira Knightley');
INSERT INTO Actor 
VALUES ('Helen Mirren');
INSERT INTO Actor 
VALUES ('Penélope Cruz');
INSERT INTO Actor 
VALUES ('Elliot Page (nominated as Ellen Page)');
INSERT INTO Actor 
VALUES ('Anne Hathaway');
INSERT INTO Actor 
VALUES ('Angelina Jolie');
INSERT INTO Actor 
VALUES ('Melissa Leo');
INSERT INTO Actor 
VALUES ('Carey Mulligan');
INSERT INTO Actor 
VALUES ('Gabourey Sidibe');
INSERT INTO Actor 
VALUES ('Andra Day');
INSERT INTO Actor 
VALUES ('Vanessa Kirby');
INSERT INTO Actor 
VALUES ('Kristen Stewart');
INSERT INTO Actor 
VALUES ('George C. Scott §');
INSERT INTO Actor 
VALUES ('Melvyn Douglas');
INSERT INTO Actor 
VALUES ('James Earl Jones');
INSERT INTO Actor 
VALUES ('Jack Nicholson');
INSERT INTO Actor 
VALUES ('Ryan O`Neal');
INSERT INTO Actor 
VALUES ('Gene Hackman');
INSERT INTO Actor 
VALUES ('Peter Finch');
INSERT INTO Actor 
VALUES ('Walter Matthau');
INSERT INTO Actor 
VALUES ('George C. Scott');
INSERT INTO Actor 
VALUES ('Topol');
INSERT INTO Actor 
VALUES ('Marlon Brando §[52]');
INSERT INTO Actor 
VALUES ('Michael Caine');
INSERT INTO Actor 
VALUES ('Laurence Olivier');
INSERT INTO Actor 
VALUES ('Peter O`Toole');
INSERT INTO Actor 
VALUES ('Paul Winfield');
INSERT INTO Actor 
VALUES ('Jack Lemmon');
INSERT INTO Actor 
VALUES ('Marlon Brando');
INSERT INTO Actor 
VALUES ('Al Pacino');
INSERT INTO Actor 
VALUES ('Robert Redford');
INSERT INTO Actor 
VALUES ('Art Carney');
INSERT INTO Actor 
VALUES ('Albert Finney');
INSERT INTO Actor 
VALUES ('Dustin Hoffman');
INSERT INTO Actor 
VALUES ('Maximilian Schell');
INSERT INTO Actor 
VALUES ('James Whitmore');
INSERT INTO Actor 
VALUES ('Peter Finch †');
INSERT INTO Actor 
VALUES ('Robert De Niro');
INSERT INTO Actor 
VALUES ('Giancarlo Giannini');
INSERT INTO Actor 
VALUES ('William Holden');
INSERT INTO Actor 
VALUES ('Sylvester Stallone');
INSERT INTO Actor 
VALUES ('Richard Dreyfuss');
INSERT INTO Actor 
VALUES ('Woody Allen');
INSERT INTO Actor 
VALUES ('Richard Burton');
INSERT INTO Actor 
VALUES ('Marcello Mastroianni');
INSERT INTO Actor 
VALUES ('John Travolta');
INSERT INTO Actor 
VALUES ('Jon Voight');
INSERT INTO Actor 
VALUES ('Warren Beatty');
INSERT INTO Actor 
VALUES ('Gary Busey');
INSERT INTO Actor 
VALUES ('Roy Scheider');
INSERT INTO Actor 
VALUES ('Peter Sellers');
INSERT INTO Actor 
VALUES ('Robert Duvall');
INSERT INTO Actor 
VALUES ('John Hurt');
INSERT INTO Actor 
VALUES ('Henry Fonda');
INSERT INTO Actor 
VALUES ('Burt Lancaster');
INSERT INTO Actor 
VALUES ('Dudley Moore');
INSERT INTO Actor 
VALUES ('Paul Newman');
INSERT INTO Actor 
VALUES ('Ben Kingsley');
INSERT INTO Actor 
VALUES ('Tom Conti');
INSERT INTO Actor 
VALUES ('Tom Courtenay');
INSERT INTO Actor 
VALUES ('F. Murray Abraham');
INSERT INTO Actor 
VALUES ('Jeff Bridges');
INSERT INTO Actor 
VALUES ('Tom Hulce');
INSERT INTO Actor 
VALUES ('Sam Waterston');
INSERT INTO Actor 
VALUES ('William Hurt');
INSERT INTO Actor 
VALUES ('Harrison Ford');
INSERT INTO Actor 
VALUES ('James Garner');
INSERT INTO Actor 
VALUES ('Dexter Gordon');
INSERT INTO Actor 
VALUES ('Bob Hoskins');
INSERT INTO Actor 
VALUES ('James Woods');
INSERT INTO Actor 
VALUES ('Michael Douglas');
INSERT INTO Actor 
VALUES ('Robin Williams');
INSERT INTO Actor 
VALUES ('Tom Hanks');
INSERT INTO Actor 
VALUES ('Edward James Olmos');
INSERT INTO Actor 
VALUES ('Max von Sydow');
INSERT INTO Actor 
VALUES ('Daniel Day-Lewis');
INSERT INTO Actor 
VALUES ('Kenneth Branagh');
INSERT INTO Actor 
VALUES ('Tom Cruise');
INSERT INTO Actor 
VALUES ('Morgan Freeman');
INSERT INTO Actor 
VALUES ('Jeremy Irons');
INSERT INTO Actor 
VALUES ('Kevin Costner');
INSERT INTO Actor 
VALUES ('Gérard Depardieu');
INSERT INTO Actor 
VALUES ('Richard Harris');
INSERT INTO Actor 
VALUES ('Anthony Hopkins');
INSERT INTO Actor 
VALUES ('Nick Nolte');
INSERT INTO Actor 
VALUES ('Robert Downey Jr.');
INSERT INTO Actor 
VALUES ('Clint Eastwood');
INSERT INTO Actor 
VALUES ('Stephen Rea');
INSERT INTO Actor 
VALUES ('Denzel Washington');
INSERT INTO Actor 
VALUES ('Laurence Fishburne');
INSERT INTO Actor 
VALUES ('Liam Neeson');
INSERT INTO Actor 
VALUES ('Nigel Hawthorne');
INSERT INTO Actor 
VALUES ('Nicolas Cage');
INSERT INTO Actor 
VALUES ('Sean Penn');
INSERT INTO Actor 
VALUES ('Massimo Troisi (posthumous)');
INSERT INTO Actor 
VALUES ('Geoffrey Rush');
INSERT INTO Actor 
VALUES ('Ralph Fiennes');
INSERT INTO Actor 
VALUES ('Woody Harrelson');
INSERT INTO Actor 
VALUES ('Billy Bob Thornton');
INSERT INTO Actor 
VALUES ('Matt Damon');
INSERT INTO Actor 
VALUES ('Peter Fonda');
INSERT INTO Actor 
VALUES ('Roberto Benigni');
INSERT INTO Actor 
VALUES ('Ian McKellen');
INSERT INTO Actor 
VALUES ('Edward Norton');
INSERT INTO Actor 
VALUES ('Kevin Spacey');
INSERT INTO Actor 
VALUES ('Russell Crowe');
INSERT INTO Actor 
VALUES ('Richard Farnsworth');
INSERT INTO Actor 
VALUES ('Colin Firth');
INSERT INTO Actor 
VALUES ('Javier Bardem');
INSERT INTO Actor 
VALUES ('Jesse Eisenberg');
INSERT INTO Actor 
VALUES ('James Franco');
INSERT INTO Actor 
VALUES ('Jean Dujardin');
INSERT INTO Actor 
VALUES ('Demián Bichir');
INSERT INTO Actor 
VALUES ('George Clooney');
INSERT INTO Actor 
VALUES ('Gary Oldman');
INSERT INTO Actor 
VALUES ('Brad Pitt');
INSERT INTO Actor 
VALUES ('Bradley Cooper');
INSERT INTO Actor 
VALUES ('Hugh Jackman');
INSERT INTO Actor 
VALUES ('Joaquin Phoenix');
INSERT INTO Actor 
VALUES ('Matthew McConaughey');
INSERT INTO Actor 
VALUES ('Christian Bale');
INSERT INTO Actor 
VALUES ('Bruce Dern');
INSERT INTO Actor 
VALUES ('Leonardo DiCaprio');
INSERT INTO Actor 
VALUES ('Chiwetel Ejiofor');
INSERT INTO Actor 
VALUES ('Eddie Redmayne');
INSERT INTO Actor 
VALUES ('Steve Carell');
INSERT INTO Actor 
VALUES ('Benedict Cumberbatch');
INSERT INTO Actor 
VALUES ('Michael Keaton');
INSERT INTO Actor 
VALUES ('Bryan Cranston');
INSERT INTO Actor 
VALUES ('Michael Fassbender');
INSERT INTO Actor 
VALUES ('Casey Affleck');
INSERT INTO Actor 
VALUES ('Andrew Garfield');
INSERT INTO Actor 
VALUES ('Ryan Gosling');
INSERT INTO Actor 
VALUES ('Viggo Mortensen');
INSERT INTO Actor 
VALUES ('Timothée Chalamet');
INSERT INTO Actor 
VALUES ('Daniel Kaluuya');
INSERT INTO Actor 
VALUES ('Rami Malek');
INSERT INTO Actor 
VALUES ('Willem Dafoe');
INSERT INTO Actor 
VALUES ('Antonio Banderas');
INSERT INTO Actor 
VALUES ('Adam Driver');
INSERT INTO Actor 
VALUES ('Jonathan Pryce');
INSERT INTO Actor 
VALUES ('Ed Harris');
INSERT INTO Actor 
VALUES ('Will Smith');
INSERT INTO Actor 
VALUES ('Tom Wilkinson');
INSERT INTO Actor 
VALUES ('Adrien Brody');
INSERT INTO Actor 
VALUES ('Johnny Depp');
INSERT INTO Actor 
VALUES ('Jude Law');
INSERT INTO Actor 
VALUES ('Bill Murray');
INSERT INTO Actor 
VALUES ('Jamie Foxx');
INSERT INTO Actor 
VALUES ('Don Cheadle');
INSERT INTO Actor 
VALUES ('Philip Seymour Hoffman');
INSERT INTO Actor 
VALUES ('Terrence Howard');
INSERT INTO Actor 
VALUES ('Heath Ledger');
INSERT INTO Actor 
VALUES ('David Strathairn');
INSERT INTO Actor 
VALUES ('Forest Whitaker');
INSERT INTO Actor 
VALUES ('Tommy Lee Jones');
INSERT INTO Actor 
VALUES ('Richard Jenkins');
INSERT INTO Actor 
VALUES ('Frank Langella');
INSERT INTO Actor 
VALUES ('Mickey Rourke');
INSERT INTO Actor 
VALUES ('Jeremy Renner');
INSERT INTO Actor 
VALUES ('Riz Ahmed');
INSERT INTO Actor 
VALUES ('Chadwick Boseman (posthumous)');
INSERT INTO Actor 
VALUES ('Steven Yeun');
INSERT INTO Actor 
VALUES ('Jonah Hill');
INSERT INTO Actor 
VALUES ('Daniel Radcliffe');
INSERT INTO Actor 
VALUES ('Emma Watson');
INSERT INTO Actor 
VALUES ('Rupert Grint');
INSERT INTO Actor 
VALUES ('Michael Gambon');
INSERT INTO Actor 
VALUES ('Katherine Waterston');
INSERT INTO Actor 
VALUES ('Dan Fogler');
INSERT INTO Actor 
VALUES ('Mads Mikkelsen');
INSERT INTO Actor 
VALUES ('Carrie Fisher');
INSERT INTO Actor 
VALUES ('Mark Hamill');
INSERT INTO Actor 
VALUES ('Ewan McGregor');
INSERT INTO Actor 
VALUES ('Hayden Christensen');
INSERT INTO Actor 
VALUES ('Daisy Ridley');
INSERT INTO Actor 
VALUES ('John Boyega');
INSERT INTO Actor 
VALUES ('Oscar Isaac');
INSERT INTO Actor 
VALUES ('Sean Astin');
INSERT INTO Actor 
VALUES ('Elijah Wood');
INSERT INTO Actor 
VALUES ('Richard Armitage');
INSERT INTO Actor 
VALUES ('Martin Freeman');
INSERT INTO Actor 
VALUES ('Evangeline Lilly');
INSERT INTO Actor 
VALUES ('Minami Takayama');
INSERT INTO Actor 
VALUES ('Rei Sakuma');
INSERT INTO Actor 
VALUES ('Kôichi Yamadera');
INSERT INTO Actor 
VALUES ('Chika Sakamoto');
INSERT INTO Actor 
VALUES ('Hitoshi Takagi');
INSERT INTO Actor 
VALUES ('Noriko Hidaka');
INSERT INTO Actor 
VALUES ('Rumi Hiiragi');
INSERT INTO Actor 
VALUES ('Miyu Irino');
INSERT INTO Actor 
VALUES ('Mari Natsuki');
INSERT INTO Actor 
VALUES ('Rufus');
INSERT INTO Actor 
VALUES ('Audrey Tautou');
INSERT INTO Actor 
VALUES ('Mathieu Kassovitz');
INSERT INTO Actor 
VALUES ('Anne Le Ny');
INSERT INTO Actor 
VALUES ('Omar Sy');
INSERT INTO Actor 
VALUES ('François Cluzet');
INSERT INTO Actor 
VALUES ('Lucy Liu');
INSERT INTO Actor 
VALUES ('Uma Thurman');
INSERT INTO Actor 
VALUES ('André Ramiro');
INSERT INTO Actor 
VALUES ('Caio Junqueira');
INSERT INTO Actor 
VALUES ('Wagner Moura');
INSERT INTO Actor 
VALUES ('Milhem Cortaz');

