-- Category
INSERT INTO Category VALUES('Ação');
INSERT INTO Category VALUES('Aventura');
INSERT INTO Category VALUES('Cinema de arte');
INSERT INTO Category VALUES('Comédia');
INSERT INTO Category VALUES('Comédia dramática');
INSERT INTO Category VALUES('Comédia romântica');
INSERT INTO Category VALUES('Dança');
INSERT INTO Category VALUES('Documentário');
INSERT INTO Category VALUES('Biográfico');
INSERT INTO Category VALUES('Drama');
INSERT INTO Category VALUES('Espionagem');
INSERT INTO Category VALUES('Faroeste');
INSERT INTO Category VALUES('Fantasia');
INSERT INTO Category VALUES('Fantasia científica');
INSERT INTO Category VALUES('Ficção científica');
INSERT INTO Category VALUES('Filmes de guerra');
INSERT INTO Category VALUES('Máfia');
INSERT INTO Category VALUES('Mistério');
INSERT INTO Category VALUES('Suspense');
INSERT INTO Category VALUES('Musical');
INSERT INTO Category VALUES('Crime');
INSERT INTO Category VALUES('Romance');
INSERT INTO Category VALUES('Terror');
INSERT INTO Category VALUES('Infantil');

-- Languages
INSERT INTO Language (language) VALUES ('Africâner‎');
INSERT INTO Language (language) VALUES ('Albanes');
INSERT INTO Language (language) VALUES ('Alemão');
INSERT INTO Language (language) VALUES ('Árabe');
INSERT INTO Language (language) VALUES ('Aramaico');
INSERT INTO Language (language) VALUES ('Armênio');
INSERT INTO Language (language) VALUES ('Asturiano');
INSERT INTO Language (language) VALUES ('Basco');
INSERT INTO Language (language) VALUES ('Bassa');
INSERT INTO Language (language) VALUES ('Bávaro');
INSERT INTO Language (language) VALUES ('Bengali');
INSERT INTO Language (language) VALUES ('Bielorrusso');
INSERT INTO Language (language) VALUES ('Bosnio');
INSERT INTO Language (language) VALUES ('Bretão');
INSERT INTO Language (language) VALUES ('Búlgaro');
INSERT INTO Language (language) VALUES ('Butanês');
INSERT INTO Language (language) VALUES ('Cantonês');
INSERT INTO Language (language) VALUES ('Castelhano');
INSERT INTO Language (language) VALUES ('Catalão');
INSERT INTO Language (language) VALUES ('Cazaque');
INSERT INTO Language (language) VALUES ('Checheno');
INSERT INTO Language (language) VALUES ('Chinês');
INSERT INTO Language (language) VALUES ('Congo');
INSERT INTO Language (language) VALUES ('Coreano');
INSERT INTO Language (language) VALUES ('Corso');
INSERT INTO Language (language) VALUES ('Croata');
INSERT INTO Language (language) VALUES ('Dinamarquês');
INSERT INTO Language (language) VALUES ('Egípsio');
INSERT INTO Language (language) VALUES ('Eslavo');
INSERT INTO Language (language) VALUES ('Eslovaco');
INSERT INTO Language (language) VALUES ('Esloveno');
INSERT INTO Language (language) VALUES ('Espanhol');
INSERT INTO Language (language) VALUES ('Esperanto');
INSERT INTO Language (language) VALUES ('Estônio');
INSERT INTO Language (language) VALUES ('Faroês');
INSERT INTO Language (language) VALUES ('Fijiano');
INSERT INTO Language (language) VALUES ('Filipino');
INSERT INTO Language (language) VALUES ('Finlandês');
INSERT INTO Language (language) VALUES ('Flamengo');
INSERT INTO Language (language) VALUES ('Francês');
INSERT INTO Language (language) VALUES ('Gaélico');
INSERT INTO Language (language) VALUES ('Galego');
INSERT INTO Language (language) VALUES ('Galês');
INSERT INTO Language (language) VALUES ('Grego');
INSERT INTO Language (language) VALUES ('Groenlandês');
INSERT INTO Language (language) VALUES ('Guarani');
INSERT INTO Language (language) VALUES ('Hebraico');
INSERT INTO Language (language) VALUES ('Hindi');
INSERT INTO Language (language) VALUES ('Húngaro');
INSERT INTO Language (language) VALUES ('Iídiche');
INSERT INTO Language (language) VALUES ('Indonésio');
INSERT INTO Language (language) VALUES ('Inglês');
INSERT INTO Language (language) VALUES ('Iorubá');
INSERT INTO Language (language) VALUES ('Irlandês');
INSERT INTO Language (language) VALUES ('Islandês');
INSERT INTO Language (language) VALUES ('Italiano');
INSERT INTO Language (language) VALUES ('Japonês');
INSERT INTO Language (language) VALUES ('Javanês');
INSERT INTO Language (language) VALUES ('Lao');
INSERT INTO Language (language) VALUES ('Lapão');
INSERT INTO Language (language) VALUES ('Latim');
INSERT INTO Language (language) VALUES ('Letônio');
INSERT INTO Language (language) VALUES ('Libras');
INSERT INTO Language (language) VALUES ('Lingala');
INSERT INTO Language (language) VALUES ('Lituano');
INSERT INTO Language (language) VALUES ('Lombardo');
INSERT INTO Language (language) VALUES ('Luxemburguês');
INSERT INTO Language (language) VALUES ('Macedônio');
INSERT INTO Language (language) VALUES ('Malaio');
INSERT INTO Language (language) VALUES ('Maltês');
INSERT INTO Language (language) VALUES ('Mam');
INSERT INTO Language (language) VALUES ('Manchu');
INSERT INTO Language (language) VALUES ('Mandarim');
INSERT INTO Language (language) VALUES ('Maori');
INSERT INTO Language (language) VALUES ('Marshalês');
INSERT INTO Language (language) VALUES ('Mongol');
INSERT INTO Language (language) VALUES ('Nepalês');
INSERT INTO Language (language) VALUES ('Nepali');
INSERT INTO Language (language) VALUES ('Persa');
INSERT INTO Language (language) VALUES ('Piemontês');
INSERT INTO Language (language) VALUES ('Polonês');
INSERT INTO Language (language) VALUES ('Português');
INSERT INTO Language (language) VALUES ('Romeno');
INSERT INTO Language (language) VALUES ('Russo');
INSERT INTO Language (language) VALUES ('Sanscrito');
INSERT INTO Language (language) VALUES ('Sardo');
INSERT INTO Language (language) VALUES ('Sérvio');
INSERT INTO Language (language) VALUES ('Siciliano');
INSERT INTO Language (language) VALUES ('Somali');
INSERT INTO Language (language) VALUES ('Sueco');
INSERT INTO Language (language) VALUES ('Tabasco');
INSERT INTO Language (language) VALUES ('Tailandês');
INSERT INTO Language (language) VALUES ('Tcheco');
INSERT INTO Language (language) VALUES ('Tibetano');
INSERT INTO Language (language) VALUES ('Turco');
INSERT INTO Language (language) VALUES ('Ucraniano');
INSERT INTO Language (language) VALUES ('Uzbeque');
INSERT INTO Language (language) VALUES ('Vietnamita');
INSERT INTO Language (language) VALUES ('Zelandês');
INSERT INTO Language (language) VALUES ('Zulu');


